name: Load Regression Data like artifact to wandb

on:
  push:
    branches:
      - main
    paths:
      - 'src/data/load_regresion.py'

jobs:
  load_regression_data: # Nombre del job adaptado
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to WandB
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Run load_regresion.py # Nombre del script a ejecutar
      run: python src/data/load_regresion.py --IdExecution ${{ github.run_number }}
