name: Train Regression Model like artifact to wandb

on:
  push:
    branches:
      - main
    paths:
      - 'src/model/train_regresion.py'

jobs:
  train_regression_model: # Nombre del job adaptado
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${GITHUB_WORKSPACE}:${PYTHONPATH}" >> $GITHUB_ENV
    - name: Login to WandB
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Run train_regresion.py from root
      run: |
        cd ${{ github.workspace }}
        python -m src.model.train_regresion --IdExecution ${{ github.run_number }}
